### ISSUE TITLE
Scoping header/footer to blockquote is not mentioned in the spec

### ISSUE THREAD

**Issue by xi** [matatk/page-structural-semantics-scanner-tests#3]
I checked, but there is nothing about blockquote in the spec:

> `footer` (scoped to the main element, a sectioning content element, or a sectioning root element other than body) - No corresponding role
> https://www.w3.org/TR/html-aam-1.0/#html-element-role-mappings

"sectioning content" is defined as one of these:  `article`, `aside`, `nav`, `section`. So headers/footers inside of blockquotes should not be ignored.

**Comment by matatk** [comment]
I think this one is actually valid as it is: the spec also mentions [sectioning root elements](https://www.w3.org/TR/html/sections.html#sectioning-roots), which includes `<blockquote>`.

**Comment by xi** [comment]
I see. Thanks for the clarification!
